<a href="https://colab.research.google.com/github/Shivam-Verma1/DLlab/blob/main/DLLab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [8]:
tf.__version__


'2.17.0'

## Part-1 Data PreProcessing

### Importing the dataset

In [14]:
dataset=pd.read_excel("/content/Folds5x2_pp.xlsx")
X =dataset.iloc[:,:-1].values  #Input as X (4 feaatures)
y=dataset.iloc[:,-1].values   #I=Output
print(X)
print(y)


[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Splitting the dataset into train and test set

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]
[473.93 467.87 431.97 ... 459.01 462.72 428.12]
[431.23 460.01 461.14 ... 473.26 438.   463.28]


## Part-2 Building ANN

Intialising the ANN

(Also known as FEED FORWARD NEURAL NETWORK OR SEQUENTIAL NEURAL NETWORK)

In [18]:
ann=tf.keras.models.Sequential()

Adding the input layer and the frst hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
# IT IS basically adding a layer with 6 neurons in this layer and non linear activation function as relu(rectified lineat unit)

# To get the output we apply Activation function at end

In [26]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the output layer

In [27]:
ann.add(tf.keras.layers.Dense(units=1))